# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

env:
  CLOUDFLARE_DNSCONTROL_TOKEN: ${{ secrets.CLOUDFLARE_DNSCONTROL_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubicloud

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
      - name: Preview
        uses: koenrh/dnscontrol-action@v3
        with:
          args: preview